apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-registry
  labels:
    app: jhipster-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-registry
  template:
    metadata:
      labels:
        app: jhipster-registry
    spec:
      containers:
        - name: jhipster-registry
          image: jhipster-registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: jhipster-registry
spec:
  ports:
    - targetPort: 8761
      port: 8761
  selector:
    app: jhipster-registry
  type: NodePort

